Repository nansencenter/nansat, pull requests merged in 2024-04, with the labels that each got.

#539 Fix logo
  .gitignore
  README.rst
  docs/source/about.rst
  docs/source/images/nansat_logo_transp.png
Labels: bug, hotfix

#537 Update setup.py for windows setup
  setup.py
Labels: enhancement

#541 Fix nansat version used in pypi build
  .github/workflows/tests_build.yml
Labels: bug
